dataset: PowerCons
slice: True
use_disc_check: True
test_run: False # If true results will be not saved!!!!

model_folder: checkpoints/${dataset}/TS2Vec/
disc_path: results/${dataset}/IFGSM
save_path: ${disc_path}/${attack_type}
 

model_id_attack: 0

attack_model:
  _target_: src.models.TS2VecClassifier
  dropout: None

# attack_model:
#   _target_: src.models.LSTM_net
#   hidden_dim: 50
#   n_layers: 1
#   output_dim: 1
#   dropout: 0.0

disc_model:
  _target_: src.models.TS2VecClassifier
  dropout: 0.3
  device: 0
  n_layers: 2


disc_model_check:
  _target_: src.models.TS2VecClassifier
  dropout: 0.0
  device: 0
  n_layers: 2

cuda: 'cuda'

attack_type: fgsm_clip_attack
n_iterations: 1
all_eps: [0.0316] #[0.03, 0.07, 0.1, 0.13, 0.17] #[0.001, 0.005, 0.0316, 0.1778, 1.0 ]  #  #[0.001, 0.01, 0.05, 0.2, 1.]
train_mode: False
batch_size: 64

alphas: [1] #[ 10, 1, 100, 0.01, 0.0001, 0.001, 0.1]

disc_check_params:
  model_id : 0
  model_name: fgsm_clip_attack/fgsm_clip_attack_eps=0.03_nsteps=10

#list_reg_model_params:
# - model_id: 0
#   model_name: 'fgsm_reg_attack/fgsm_reg_attack_eps=0.0316_alpha=1_nsteps=20'
# - model_id: 0
#   model_name: 'fgsm_reg_attack/fgsm_reg_attack_eps=0.0316_alpha=10_nsteps=50'
# - model_id: 1
#   model_name: 'fgsm_reg_attack/fgsm_reg_attack_eps=0.0056_alpha=1_nsteps=50'
# - model_id: 1
#   model_name: 'fgsm_reg_attack/fgsm_reg_attack_eps=0.0056_alpha=10_nsteps=50'








